
version: "3.3"
services:
    backend:
        build:
            context: ".."
            dockerfile: "docker/Dockerfile-backend"
        depends_on:
            - "pg"
        environment:
            - "PORT=8090"
            - "KITTY_DB_CONN_STR=postgres://kitty-cat-map:foobar@pg:5432/kitty-cat-map"
            - "KITTY_IMG_DIR=/var/lib/kitty-cat-map/images"
        expose:
            - "8090"
        image: "kitty-cat-map-backend"
        ports:
            - "8090:8090"
        volumes:
            - type: volume
              source: images
              target: "/var/lib/kitty-cat-map/images"
              read_only: false
              volume:
                nocopy: true
    pg:
        image: "mdillon/postgis:9.6-alpine"
        environment:
            POSTGRES_DB: kitty-cat-map
            POSTGRES_PASSWORD: foobar
            POSTGRES_USER: kitty-cat-map
        volumes:
            - type: volume
              source: db
              target: "/var/lib/postgresql/data"
              read_only: false
              volume:
                nocopy: true
        expose:
            - "5432"
        ports:
            - "5432:5432"

volumes:
  # This holds the database files for PostgreSQL.
  db:
  # This holds the images uploaded by the users.
  images:
