
version: "3.3"
services:
    pg:
        image: "mdillon/postgis:9.6-alpine"
        environment:
            POSTGRES_DB: kitty-cat-map
            POSTGRES_PASSWORD: foobar
            POSTGRES_USER: kitty-cat-map
        volumes:
            - type: volume
              source: db
              target: "/var/lib/postgresql/data"
              read_only: false
              volume:
                nocopy: true
        expose:
            - "5432"
        ports:
            - "5432:5432"

volumes:
  db:
