
version: "3.3"
services:
    backend:
        build:
            context: ".."
            dockerfile: "docker/Dockerfile-backend"
        depends_on:
            - "pg"
        environment:
            - "PORT=8090"
        expose:
            - "8090"
        image: "kitty-cat-map-backend"
        ports:
            - "8090:8090"
        # volumes:
        #     - "..:/opt/kitty-cat-map-backend"
    pg:
        image: "mdillon/postgis:9.6-alpine"
        environment:
            POSTGRES_DB: kitty-cat-map
            POSTGRES_PASSWORD: foobar
            POSTGRES_USER: kitty-cat-map
        volumes:
            - type: volume
              source: db
              target: "/var/lib/postgresql/data"
              read_only: false
              volume:
                nocopy: true
        expose:
            - "5432"
        ports:
            - "5432:5432"

volumes:
  db:
