FROM debian:9.1

ENV RESOLVER "lts-9.6"

# Add "/root/.local/bin" to the PATH because that is where stack stores
# binaries.
ENV PATH "/root/.local/bin:$PATH"

RUN apt-get update && \
    apt-get install -y \
        bash \
        binutils \
        ca-certificates \
        coreutils \
        curl \
        gcc \
        gnupg \
        grep \
        libpq-dev \
        tree \
        zlib1g-dev && \
    (curl https://get.haskellstack.org/ | sh)

# Update stack's index.
RUN stack --no-terminal update

# Install GHC for resolver.
RUN stack --no-terminal --resolver "$RESOLVER" setup

# Install some big packages before the COPY command so they don't have to be
# reinstalled everytime this dockerfile is rebuilt.
RUN stack --no-terminal --resolver "$RESOLVER" install \
        aeson \
        attoparsec-iso8601 \
        base-noprelude \
        binary \
        bytestring \
        classy-prelude \
        cryptonite \
        cryptonite-conduit \
        directory \
        filepath \
        http-api-data \
        lens \
        monad-logger \
        mtl \
        postgresql-simple \
        read-env-var \
        resource-pool \
        resourcet \
        servant-checked-exceptions \
        servant-multipart \
        servant-server \
        text \
        transformers-base \
        uuid \
        wai-app-static \
        warp

# Create directory to use as volume when running the image.
RUN mkdir -p /opt/kitty-cat-map-backend
WORKDIR /opt/kitty-cat-map-backend
COPY . /opt/kitty-cat-map-backend

RUN stack --no-terminal install

ENTRYPOINT ["/bin/sh", "-c" , "/root/.local/bin/kitty-cat-map-server ; tail -f /dev/null"]
