FROM alpine:3.6

RUN apk update && \
    apk add \
        alpine-sdk \
        bash \
        binutils \
        build-base \
        ca-certificates \
        coreutils \
        findutils \
        gcc \
        ghc \
        gmp-dev \
        gnupg \
        grep \
        libffi-dev \
        libpq \
        linux-headers \
        musl-dev \
        util-linux \
        zlib-dev && \
    (wget -qO- https://get.haskellstack.org/ | sh)

# Update stack's index.
RUN stack --no-terminal update

# Install some big packages before the COPY command so they don't have to be
# reinstalled everytime this dockerfile is rebuilt.
RUN stack --no-terminal --resolver lts-9.2 --system-ghc install \
        aeson \
        attoparsec-iso8601 \
        binary \
        bytestring \
        classy-prelude \
        cryptonite \
        cryptonite-conduit \
        directory \
        filepath \
        http-api-data \
        lens \
        monad-logger \
        mtl \
        postgresql-simple \
        read-env-var \
        resource-pool \
        resourcet \
        servant-checked-exceptions \
        servant-multipart \
        servant-server \
        text \
        transformers-base \
        uuid \
        wai-app-static \
        warp

# Create directory to use as volume when running the image.
RUN mkdir -p /opt/kitty-cat-map-backend
WORKDIR /opt/kitty-cat-map-backend
COPY . /opt/kitty-cat-map-backend

RUN stack --no-terminal --system-ghc build

ENTRYPOINT ["/bin/sh", "-c" , "tail -f /dev/null"]
