
version: "3.3"
services:
    pg:
        image: "mdillon/postgis:9.6-alpine"
        environment:
            POSTGRES_DB: kitty-cat-map
            POSTGRES_PASSWORD: foobar
            POSTGRES_USER: kitty-cat-map
        volumes:
            - "./db:/var/lib/postgresql/data"
        expose:
            - "5432"
        ports:
            - "5432:5432"
